import styles from "./Myreact.module.css";
function Myreact() {
  const images = [
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
    {
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReLyRAfB8rBKl8AsfBciSq7OucaCorv8TP8iBPyd7a&s",
    },
  ];

  const externalImage =
    "https://i.pinimg.com/474x/cc/e0/78/cce078329ede2e53f7dde2d205e93c79.jpg";

  return (
    <div className={styles.card}>
      <div className={styles.ayshu}>
        {images.map((i) => (
          <div
            style={{
              backgroundImage: `url(${i.image})`,
            }}
            className={styles.timtim1}
          ></div>
        ))}
      </div>
    </div>
  );
}

export default Myreact;
